# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Marvis
tagline:          Sivaram Ambikasaran
url:              http://http://sivaramambikasaran.github.io/
paginate:         1
baseurl:          /
author:
  name:           Sivaram Ambikasaran
  url:            http://http://sivaramambikasaran.github.io/
  email:          siva.1985@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/sivaramambikasaran/sivaramambikasaran.github.io
